version: "3"
services:
  manager:
    build: .
    depends_on:
      - db
    environment: 
      POSTGRES_USER: username
      POSTGRES_PASSWORD: userpassword
      POSTGRES_DB: db
      CSV_FILENAME: data.csv

  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: userpassword
      POSTGRES_DB: db
 
  
  
 